# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work-space\eric6\learn0410\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 685)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777209))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Cherokee, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 550, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 550, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 40, 701, 481))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(100, 550, 101, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 550, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 550, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralWidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actiondakai = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/source/icon/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondakai.setIcon(icon)
        self.actiondakai.setObjectName("actiondakai")
        self.actionguanbi = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/source/icon/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionguanbi.setIcon(icon1)
        self.actionguanbi.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionguanbi.setObjectName("actionguanbi")
        self.actiontuichu = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/source/icon/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontuichu.setIcon(icon2)
        self.actiontuichu.setObjectName("actiontuichu")
        self.actionshiyongshuoming = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/source/icon/About.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionshiyongshuoming.setIcon(icon3)
        self.actionshiyongshuoming.setObjectName("actionshiyongshuoming")
        self.actionguanyu = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/source/icon/contact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionguanyu.setIcon(icon4)
        self.actionguanyu.setObjectName("actionguanyu")
        self.toolBar.addSeparator()
        self.menu.addAction(self.actiondakai)
        self.menu.addAction(self.actionguanbi)
        self.menu.addAction(self.actiontuichu)
        self.menu_2.addAction(self.actionshiyongshuoming)
        self.menu_3.addAction(self.actionguanyu)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "选定文件夹"))
        self.pushButton_2.setText(_translate("MainWindow", "开始搜索"))
        self.label.setText(_translate("MainWindow", "请输入关键词："))
        self.pushButton_3.setText(_translate("MainWindow", "清空"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.actiondakai.setText(_translate("MainWindow", "打开"))
        self.actionguanbi.setText(_translate("MainWindow", "保存"))
        self.actionguanbi.setIconText(_translate("MainWindow", "baocun"))
        self.actionguanbi.setToolTip(_translate("MainWindow", "baocun"))
        self.actiontuichu.setText(_translate("MainWindow", "退出"))
        self.actionshiyongshuoming.setText(_translate("MainWindow", "使用说明"))
        self.actionguanyu.setText(_translate("MainWindow", "关于我们"))

import my_pic_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

